name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker-publish-image:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate Image Tags
          id: gen_tags
          run: |
            if [[ $GITHUB_REF == 'refs/tags/v'* ]]; then
              TAGS='["${{ secrets.DOCKER_HUB_USERNAME }}/wpilib:latest","${{ secrets.DOCKER_HUB_USERNAME }}/wpilib:'${GITHUB_REF/refs\/tags\//}'"]'
            else
              TAGS='["${{ secrets.DOCKER_HUB_USERNAME }}/wpilib:latest"]'
            fi
            echo '::set-output name=tags::'$TAGS
      -
        name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64
          push: true
          file: dockerfiles/Dockerfile-wpilib
          tags: ${{ fromJson(steps.gen_tags.outputs.tags) }}
